import type { Metadata } from "next";
import "./globals.css";
import { NavigationMenuDemo } from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import { Lora } from "next/font/google";

const openLora = Lora({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openLora.className}>
        {/* <Header /> */}
        <NavigationMenuDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
